# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6187215ecd6c87537a40d51f4b99e5a2128b9bdc335bad76ce841a9643119778e84a81eb5a5c44ec6997139e9ea2e4e24712735608b8eb1dbee72fd145ebd2b2

test:
  secret_key_base: 9e072707d21379a904611b984220cee39474c3eb68ee85039341608d17d9bdb82da9abddcc5850012b4d5dadf7f36d0097aa8368de6df0d68fdb78390fb7b31f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
